### ISSUE TITLE
play nicer with lists

### ISSUE THREAD

**Issue by nsheff** [databio/yacman#14]
I believe our internal representation doesn't handle lists nicely. but lists are valid yaml.

```
yacman.YacAttMap(['a', 'b', 'c'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nsheff/.local/lib/python3.7/site-packages/yacman/yacman.py", line 52, in __init__
    super(YacAttMap, self).__init__(entries or {})
  File "/home/nsheff/.local/lib/python3.7/site-packages/attmap/ordattmap.py", line 22, in __init__
    super(OrdAttMap, self).__init__(entries or {})
ValueError: need more than 1 value to unpack
```

```
yacman.YacAttMap(yamldata="item1: item2\n")
item1: item2

yacman.YacAttMap(yamldata="-item1\n-item2\n")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nsheff/.local/lib/python3.7/site-packages/yacman/yacman.py", line 52, in __init__
    super(YacAttMap, self).__init__(entries or {})
  File "/home/nsheff/.local/lib/python3.7/site-packages/attmap/ordattmap.py", line 22, in __init__
    super(OrdAttMap, self).__init__(entries or {})
ValueError: need more than 1 value to unpack
```

current:
```
yacman.YacAttMap({'lst': ['a', 'b', 'c']})
lst: ['a', 'b', 'c']
```
better:

```
yacman.YacAttMap({'lst': ['a', 'b', 'c']})
lst:
  - 'a'
  - 'b
  - 'c'
```

**Comment by nsheff** [comment]
not a problem with `yaml.load()`, which can handle top-level lists.

**Comment by stolarczyk** [comment]
resolved
```python
In [1]: import yacman                                                                                                                                                                                     
yacman.YacAttMap({'lst': ['a', 'b', 'c']})  
In [2]: yacman.YacAttMap({'lst': ['a', 'b', 'c']})                                                                                                                                                        
Out[2]: 
lst: 
 - a
 - b
 - c
 ```

**Comment by nsheff** [comment]
Hmmm... that's on the second part. 

The real point of this was that top-level lists don't work, and I think they still don't:


```
In [1]: import yacman

yacman.__version__
Out[5]: '0.8.0-dev'


In [2]: yacman.YacAttMap(['a', 'b', 'c'])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-3167fe09a054> in <module>
----> 1 yacman.YacAttMap(['a', 'b', 'c'])

~/code/yacman/yacman/yacman.py in __init__(self, entries, filepath, yamldata, writable, wait_max, skip_read_lock, schema_source, write_validate)
    116         elif yamldata:
    117             entries = yaml.load(yamldata, yaml.SafeLoader)
--> 118         super(YacAttMap, self).__init__(entries or {})
    119         if filepath:
    120             # to make this python2 compatible, the attributes need to be set here.

~/.local/lib/python3.8/site-packages/attmap/ordattmap.py in __init__(self, entries)
     20 
     21     def __init__(self, entries=None):
---> 22         super(OrdAttMap, self).__init__(entries or {})
     23 
     24     def __setattr__(self, name, value):

ValueError: need more than 1 value to unpack
```

**Comment by nsheff** [comment]
I believe I've solved in this in the new implementation, using the YAMLConfigManager object. Also added tests.

**Comment by nsheff** [comment]
Confirmed this works with the new object.
